const LOGIN_2_LEGGED = "autodesk__LOGIN_2_LEGGED";
const LOGIN_3_LEGGED = "autodesk__LOGIN_3_LEGGED";
const LOGOUT_3_LEGGED = "autodesk__LOGOUT_3_LEGGED";
const FETCH_PROJECT_INFO = "autodesk__FETCH_PROJECT_INFO";
const FETCH_USER_INFO = "autodesk__FETCH_USER_INFO";

export default {
    LOGIN_2_LEGGED,
    LOGIN_3_LEGGED,
    LOGOUT_3_LEGGED,
    FETCH_PROJECT_INFO,
    FETCH_USER_INFO,
};
