const LOGIN_2_LEGGED = "LOGIN_2_LEGGED";
const LOGIN_3_LEGGED = "LOGIN_3_LEGGED";
const LOGOUT_3_LEGGED = "LOGOUT_3_LEGGED";
const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";

export default {
      LOGIN_2_LEGGED,
      LOGIN_3_LEGGED,
      LOGOUT_3_LEGGED,
      FETCH_USER_DETAIL,
};
