const FETCH_ALL_PROJECTS = "FETCH_ALL_PROJECTS";
const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
const SET_PROJECT_TOP_FOLDER = "SET_PROJECT_TOP_FOLDER";
const CLEAR_ALL_DATA = "CLEAR_ALL_DATA";
const CLEAR_PROJECT_TOP_FOLDER = "CLEAR_PROJECT_TOP_FOLDER";

export default {
      FETCH_ALL_PROJECTS,
      SET_CURRENT_PROJECT,
      SET_PROJECT_TOP_FOLDER,
      CLEAR_PROJECT_TOP_FOLDER,
      CLEAR_ALL_DATA,
};
