export const CONSTANTS = {
	RESULTS: 'RESULTS',
	PROGRESS: 'PROGRESS',
	TERMS: 'TERMS',
};

export const TERM_TYPE = {
	REAL_START: 'REAL_START',
	PLANNED_FINISH: 'PLANNED_FINISH',
	REAL_FINISH: 'REAL_FINISH',
};
