export enum General {
	SELECT_WORKER_TYPE = 'workers_log__SELECT_WORKER_TYPE',
	SET_DATE_RANGE = 'workers_log__SET_DATE_RANGE',
	SET_CALENDAR = 'workers_log__SET_CALENDAR',
	GENERATE_RAPORT_START = 'workers_log__GENERATE_RAPORT_START',
	GENERATE_RAPORT_END = 'workers_log__GENERATE_RAPORT_END',
}
