const crewActionTypes = {
	FETCH_CREW_START: 'FETCH_CREW_START',
	FETCH_CREW_END: 'FETCH_CREW_END',
	FETCH_CREW_ERROR: 'FETCH_CREW_ERROR',

	FETCH_CREWS_OPTIONS_START: 'FETCH_CREWS_OPTIONS_START',
	FETCH_CREWS_OPTIONS_END: 'FETCH_CREWS_OPTIONS_END',
	FETCH_CREWS_OPTIONS_ERROR: 'FETCH_CREWS_OPTIONS_ERROR',

	CHOOSE_CREW: 'CHOOSE_CREW',
	ADD_CREW: 'ADD_CREW',
};

export default class WorkersLogActions {
	static CREW_ACTION_TYPES = crewActionTypes;
}
