export enum Crew {
	FETCH_START = 'workers_log__FETCH_CREW_START',
	FETCH_END = 'workers_log__FETCH_CREW_END',
	FETCH_ERROR = 'workers_log__FETCH_CREW_ERROR',

	FETCH_CREW_SUMMARIES_START = 'workers_log__FETCH_CREW_SUMMARIES_START',
	FETCH_CREW_SUMMARIES_END = 'workers_log__FETCH_CREW_SUMMARIES_END',
	FETCH_CREW_SUMMARIES_ERROR = 'workers_log__FETCH_CREW_SUMMARIES_ERROR',

	// FETCH_OPTIONS_START = 'workers_log__FETCH_CREWS_OPTIONS_START',
	// FETCH_OPTIONS_END = 'workers_log__FETCH_CREWS_OPTIONS_END',
	// FETCH_OPTIONS_ERROR = 'workers_log__FETCH_CREWS_OPTIONS_ERROR',

	CHOOSE = 'workers_log__CHOOSE_CREW',
	ADD = 'workers_log__ADD_CREW',

	UPDATE_CREW_SUMMARY = "workers_log__UPDATE_CREW_SUMMARY"
}
