export enum Crew {
    FETCH_START = 'FETCH_CREW_START',
    FETCH_END = 'FETCH_CREW_END',
    FETCH_ERROR = 'FETCH_CREW_ERROR',

    FETCH_OPTIONS_START = 'FETCH_CREWS_OPTIONS_START',
    FETCH_OPTIONS_END = 'FETCH_CREWS_OPTIONS_END',
    FETCH_OPTIONS_ERROR = 'FETCH_CREWS_OPTIONS_ERROR',

    CHOOSE = 'CHOOSE_CREW',
    ADD = 'ADD_CREW',
}