export enum TimeEvidence {
	SET_INITIAL = "workers_log__TIME_EVIDENCE__SET_INITIAL",

	FETCH_WORKER_TIME_EVIDENCE_START = 'workers_log__FETCH_WORKER_TIME_EVIDENCE_START',
	FETCH_WORKER_TIME_EVIDENCE_END = 'workers_log__FETCH_WORKER_TIME_EVIDENCE_END',
	FETCH_WORKER_TIME_EVIDENCE_FINISH_ALL = 'workers_log__FETCH_WORKER_TIME_EVIDENCE_FINISH_ALL',
	FETCH_WORKER_TIME_EVIDENCE_ERROR = 'workers_log__FETCH_WORKER_TIME_EVIDENCE_ERROR',

	EDITING_START = 'workers_log__EDITING_START',
	EDITING_WORKED_TIME_INIT = 'workers_log__EDITING_WORKED_TIME_INIT',
	EDITING_WORKED_TIME_SUCCEED = 'workers_log__EDITING_WORKED_TIME_SUCCEED',
	EDITING_WORKED_TIME_ABORTED = 'workers_log__EDITING_WORKED_TIME_ABORTED',
	EDITING_CANCEL = 'workers_log__EDITING_CANCEL',
	EDITING_END = 'workers_log__EDITING_END',
}
